image: python:latest

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python --version  # For debugging
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install jupyter

test:
  script:
    - cd src/
    - jupyter nbconvert --to script IFRS17SoftwareCode-GMM.ipynb
    - python IFRS17SoftwareCode-GMM.py

push-back-to-remote:
  script:
    - git config user.email "patrickmoehrke@dupro.co.uk"
    - git config user.name "ci-bot"
    - git remote add gitlab_origin https://oauth2:$ACCESS_TOKEN@gitlab.com/patrickmoehrke/ifrs17-calculation-app.git
    - cd src/
    - jupyter nbconvert --to script IFRS17SoftwareCode-GMM.ipynb
    - git add .
    - git commit -m 'Add .py version of notebook'
    - git push gitlab_origin HEAD:main -o ci.skip # prevent triggering pipeline again
